name: Binary Ready - Veracode Static Code Analysis

run-name: ${{ github.event.action == 'binary-ready-veracode-sast-pipeline-scan1' && Binary Ready - Static Code Analysis - ${{ github.event.client_payload.repository.name }} || Veracode Pipeline Scan Baseline Generation - ${{ github.event.client_payload.repository.name }}

concurrency:
  group: ${{ github.event.client_payload.event_type }}-${{ github.event.client_payload.repository.name }}-${{ github.event.client_payload.branch }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types: [binary-ready-veracode-sast-pipeline-scan]

jobs:
  create-checks-run:
    name: Create Checks Run
    runs-on: ubuntu-latest
    steps:
    - uses: veracode/veracode-checks-action@main
      name: Create Checks Run
      id: create_checks_run
      with:
        token: ${{ github.event.client_payload.token }}
        repo: ${{ github.event.client_payload.repository.full_name }}
        sha: ${{ github.event.client_payload.sha }}
        name: ${{ github.event.action == 'binary-ready-veracode-sast-pipeline-scan' && 'Veracode Static Code Analysis' || 'Veracode Pipeline Scan Baseline File Generation' }}
        status: 'in_progress'
        details_url: "https://github.com/${{ github.event.client_payload.repository.owner }}/veracode/actions/runs/${{ github.run_id }}"
    - name: Create metadata
      id: create_metadata_json
      run: |
        echo '{
          "check_run_type": "${{ github.event.client_payload.event_type }}",
          "repository_name": "${{ github.event.client_payload.repository.name }}",
          "check_run_id": ${{ steps.create_checks_run.outputs.check_id }},
          "sha": "${{ github.event.client_payload.sha }}"
        }' > workflow-metadata.json
    - name: Save metadata
      uses: actions/upload-artifact@v3
      with:
        name: workflow-metadata
        path: workflow-metadata.json
        
  pipeline_scan:
    needs: create-checks-run
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ github.event.client_payload.token }}
        run-id: ${{ github.event.client_payload.run_id }}
        repository: ${{ github.event.client_payload.repository.full_name }}
        name: veracode-artifact
        path: ./veracode-artifact
    - name: Get the name of the downloaded files
      run: |
        artifact_file=$(ls -1 ./veracode-artifact | head -n 1)
        echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
    - name: Veracode Pipeline-Scan
      id: pipeline-scan
      uses: veracode/Veracode-pipeline-scan-action@v1.0.10
      with:
        vid: ${{ secrets.VERACODE_API_ID }}
        vkey: ${{ secrets.VERACODE_API_KEY }}
        file: ./veracode-artifact/${{ env.veracode_artifact }}
        fail_build: true
        # include: bin/Verademo-dotnet.dll
