name: Binary Ready - Veracode Static Code Analysis

run-name: ${{ format('{0} - {1}', github.event.action == 'binary-ready-veracode-sast-pipeline-scan' && 'Binary Ready - Static Code Analysis' || 'Veracode Pipeline Scan Baseline Generation', github.event.client_payload.repository.name) }}

concurrency:
  group: ${{ github.event.client_payload.event_type }}-${{ github.event.client_payload.repository.name }}-${{ github.event.client_payload.branch }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types:
      - binary-ready-veracode-sast-pipeline-scan
      - sast-pipeline-baseline-scan

jobs:
  create-checks-run:
    name: Create Checks Run
    runs-on: ubuntu-latest
    steps:
    - uses: veracode/veracode-checks-action@main
      name: Create Checks Run
      id: create_checks_run
      with:
        token: ${{ inputs.token }}
        repo: ${{ inputs.owner }}/${{ inputs.repository }}
        sha: ${{ inputs.sha }}
        name: ${{ inputs.name }}
        status: 'in_progress'
        details_url: "https://github.com/${{ inputs.owner }}/veracode/actions/runs/${{ inputs.run_id }}"
    - name: Create metadata
      id: create_metadata_json
      run: |
        echo '{
          "check_run_type": "${{ inputs.event_type }}",
          "repository_name": "${{ inputs.repository }}",
          "check_run_id": ${{ steps.create_checks_run.outputs.check_id }},
          "sha": "${{ inputs.sha }}"
        }' > workflow-metadata.json
    - name: Save metadata
      uses: actions/upload-artifact@v3
      with:
        name: workflow-metadata
        path: workflow-metadata.json

  pipeline_scan:
    # needs: create-checks-run
    uses: ./.github/workflows/veracode-pipeline-scan.yml
    with:
      repository: ${{ github.event.client_payload.repository.full_name }}
      run_id: ${{ github.event.client_payload.run_id }}
      token: ${{ github.event.client_payload.token }}
    secrets: inherit
