name: Veracode Software Composition Analysis

run-name: Software Composition Analysis - ${{ github.event.client_payload.repository.name }}

concurrency:
  group: ${{ github.event.client_payload.event_type }}-${{ github.event.client_payload.repository.name }}-${{ github.event.client_payload.branch }}
  cancel-in-progress: true

on:
  repository_dispatch:
    types: [veracode-sca-scan]
    
jobs:
  create-checks-run:
    uses: ./.github/workflows/create-checks-run.yml
    with:
      token: ${{ github.event.client_payload.token }}
      repository: ${{ github.event.client_payload.repository.name }}
      sha: ${{ github.event.client_payload.sha }}
      name: 'Veracode Static Code Analysis'
      run_id: ${{ github.run_id }}
      owner: ${{ github.event.client_payload.repository.owner }}
      event_type: ${{ github.event.client_payload.event_type }}
    secrets: inherit
       
  veracode-sca-scan:
    needs: [create-checks-run]
    runs-on: ubuntu-latest
    name: Veracode Component Analysis

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false  
          debug: false
