name: Build Artifact for Veracode Code Analysis

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
      event_name:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/veracode-build-${{ inputs.event_name }}.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}
  # build-java-maven:
  #   if: ${{ inputs.event_name == 'java-maven' }}
  #   uses: ./.github/workflows/veracode-build-java-maven.yml
  #   with:
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #     token: ${{ inputs.token }}

  # build-java-gradle:
  #   if: ${{ inputs.event_name == 'java-gradle-pipeline-scan' || inputs.event_name == 'java-gradle-policy-scan' }}
  #   uses: ./.github/workflows/veracode-build-java-gradle.yml
  #   with:
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #     token: ${{ inputs.token }}

  # build-source-code-scan:
  #   if: ${{ inputs.event_name == 'source-code-pipeline-scan' || inputs.event_name == 'source-code-policy-scan' }}
  #   uses: ./.github/workflows/veracode-build-source-code.yml
  #   with:
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #     token: ${{ inputs.token }}

  # build-dot-net-package:
  #   if: ${{ inputs.event_name == 'dot-net-pipeline-scan' || inputs.event_name == 'dot-net-policy-scan' }}
  #   uses: ./.github/workflows/veracode-build-dot-net.yml
  #   with:
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #     token: ${{ inputs.token }}

  # build-go-package:
  #   if: ${{ inputs.event_name == 'go-pipeline-scan' || inputs.event_name == 'go-policy-scan' }}
  #   uses: ./.github/workflows/veracode-build-go.yml
  #   with:
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #     token: ${{ inputs.token }}

  # build-dart-package:
  #   if: ${{ inputs.event_name == 'dart-pipeline-scan' || inputs.event_name == 'dart-policy-scan' }}
  #   uses: ./.github/workflows/veracode-build-dart.yml
  #   with:
  #     repository: ${{ inputs.repository }}
  #     ref: ${{ inputs.ref }}
  #     token: ${{ inputs.token }}
